tags:
- name: users
  description: users API
- name: ai-agent
  description: AI Agent API for natural language database queries

paths:
# [GET] users
  /users:
    get:
      tags:
      - users
      summary: Find All Users
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] users
    post:
      tags:
      - users
      summary: Add User
      parameters:
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        201:
          description: 'Created'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] users/id
  /users/{id}:
    get:
      tags:
      - users
      summary: Find User By Id
      parameters:
      - name: id
        in: path
        description: User Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [PUT] users/id
    put:
      tags:
      - users
      summary: Update User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      - name: body
        in: body
        description: user Data
        required: true
        schema:
          $ref: '#/definitions/users'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [DELETE] users/id
    delete:
      tags:
      - users
      summary: Delete User By Id
      parameters:
      - name: id
        in: path
        description: user Id
        required: true
      responses:
        200:
          description: 'OK'
        409:
          description: 'Conflict'
        500:
          description: 'Server Error'

# [GET] ai-agent/status
  /api/ai-agent/status:
    get:
      tags:
      - ai-agent
      summary: Get AI Agent Status
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [GET] ai-agent/samples
  /api/ai-agent/samples:
    get:
      tags:
      - ai-agent
      summary: Get Sample Queries
      responses:
        200:
          description: 'OK'
        500:
          description: 'Server Error'

# [POST] ai-agent/query
  /api/ai-agent/query:
    post:
      tags:
      - ai-agent
      summary: Process Natural Language Query
      parameters:
      - name: body
        in: body
        description: Natural language query
        required: true
        schema:
          $ref: '#/definitions/aiQuery'
      responses:
        200:
          description: 'OK'
        400:
          description: 'Bad Request'
        500:
          description: 'Server Error'

# definitions
definitions:
  users:
    type: object
    required:
        - email
        - password
    properties:
      email:
        type: string
        description: user Email
      password:
        type: string
        description: user Password

  aiQuery:
    type: object
    required:
        - query
    properties:
      query:
        type: string
        description: Natural language query for database operations
        minLength: 3
        maxLength: 500
        example: "Get all users with Gmail email addresses"

schemes:
 - https
 - http
